CREATE USER new_user3 WITH PASSWORD 'password';

GRANT USAGE ON SCHEMA ecommerce TO new_user3;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ecommerce TO new_user3;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecommerce GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO new_user3;
GRANT USAGE, SELECT ON SEQUENCE ecommerce.customers_customer_id_seq TO new_user3;