
CREATE USER new_user2 WITH PASSWORD 'password';

GRANT USAGE ON SCHEMA ecommerce TO new_user2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ecommerce TO new_user2;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecommerce GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO new_user2;